language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

before_deploy:
  - zip -r sangsang-webservice *
  - mkdir -p deploy
  - mv sangsang-webservice.zip deploy/sangsang-webservice.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: sangsang-webservice-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: sangsang-webservice-build
    key: sangsang-webservice.zip
    bundle_type: zip
    application: sangsang-webservice
    deployment_group: sangsang-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI Email Alarm
notifications:
  email:
    recipients:
      - sanghun1984@gmail.com